openapi: 3.0.0
info:
  title: Ignite Project Tasks API
  description: API endpoints for managing tasks within the Ignite project. This includes creating, retrieving, updating, and deleting tasks.
  version: 1.0.0
servers:
  - url: https://api.ignite.webally.co.za/
    description: Main production server for task management

paths:
  /tasks/{project}:
    get:
      summary: Get All Tasks in a Project
      description: Retrieve all tasks associated with a given project.
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
          description: The project identifier
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of tasks for the specified project.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{project}/{task_id}:
    get:
      summary: Get a Specific Task in a Project
      description: Retrieve details of a specific task within a project.
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detailed information about the specific task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{project}/{task_id}:
    put:
      summary: Update a Task in a Project
      description: Update the details of a specific task within a project.
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                status:
                  type: boolean
      responses:
        '200':
          description: Task successfully updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{project}/{task_id}:
    delete:
      summary: Delete a Task in a Project
      description: Delete a specific task within a project.
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task successfully deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        status:
          type: boolean

    Error:
      type: object
      properties:
        message:
          type: string
